<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget_Collection */
$productCollection = $this->getData('collection');
$count = $productCollection ? $productCollection->count() : 0;
$carousel = $this->getData('carousel');
$row = $this->getData('row');
$column = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper = Mage::helper('catalog/image');
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i = 0;
    foreach ($productCollection as $_product): ?>
        <?php /* @var $_product Mage_Catalog_Model_Product */ ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        <div class="row">
        <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
    <?php endif ?>
        <?php $i++ ?>
        <li class="item col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="product-item">
                <div class="product-hover">
                    <div class="product-hover-inner">
                        <div class="product-hover-inner">
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                               class="product-image img-responsive">
                                <?php echo $this->helper('mtbejewelry')->getLabel($_product); ?>
                                <span class="front margin-image">
                                    <?php if ($carousel == 1): ?>
                                        <img
                                            data-src="<?php echo $helper->init($_product, 'small_image')->resize(370, 413); ?>"
                                            src="<?php echo $this->getSkinUrl('images/loader.gif') ?>"
                                            class="lazyOwl img-responsive lazy <?php echo $hoveraltClass; ?>"
                                            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                    <?php else: ?>
                                        <img
                                            src="<?php echo $helper->init($_product, 'small_image')->resize(370, 413); ?>"
                                            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                    <?php endif ?>
                            </span>
                            </a>

                            <div class="product-intification-box"><i class="fa fa-circle-o-notch fa-spin"></i></div>
                        </div>

                        <div class="bottom-product">
                            <div class="bottom-product-content">
                                <h3 class="product-name">
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                        <?php echo $this->escapeHtml($_product->getName()) ?>
                                    </a>
                                </h3>

                                <div class="table"><?php echo $this->getPriceHtml($_product, true) ?></div>
                                <div class="confix-produclist-category">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php if (!($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped())) { ?>
                                            <button type="button" title="<?php echo $this->__('Add To Cart') ?>"
                                                    data-placement="top"
                                                    class="button btn-cart mt-tooltip <?php if ($oType == true) echo 'option-file'; ?>"
                                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                <span>
                                                    <span><?php echo $this->__("Add to cart"); ?></span>
                                                </span>
                                            </button>
                                        <?php } else { ?>
                                            <?php if (Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) : ?>
                                                <a style="display: none;"
                                                   href='<?php echo $this->getUrl('ajaxcart/index/options', array('product_id' => $_product->getId())); ?>'
                                                   class='options-cart'
                                                   data-id='options-cart-<?php echo $_product->getId() ?>'><?php echo $this->__('Option cart') ?></a>
                                            <?php endif; ?>

                                            <button type="button" title="<?php echo $this->__('Add To Cart') ?>"
                                                    data-placement="top"
                                                    class="button btn-cart show-options mt-tooltip"
                                                    data-id="<?php echo $_product->getId(); ?>"
                                                <?php if (!Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) { ?>
                                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"
                                                <?php } ?>
                                                    data-submit='<?php echo $this->getAddToCartUrl($_product) ?>'>
                                                <span>
                                                   <span><?php echo $this->__("Add to cart"); ?></span>
                                                </span>
                                            </button>

                                        <?php } ?>
                                    <?php else: ?>
                                        <p class="availability out-of-stock">
                                            <span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        </ul>
        </div>
    <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
