<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget */
$id = $this->getConfig('id');
$title = $this->getConfig('widget_title');
$tabs = $this->getTabs();
$template = 'mt/widget/collection.phtml';
$t = microtime();
?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
    <?php if ($title): ?>
        <h2><?php echo $title ?></h2>
    <?php endif ?>
    <ul class="widget-tabs nav nav-tabs">
        <?php $i=0; $sizeList = sizeof($tabs); foreach ($tabs as $index => $tab): ?>
            <li class="<?php $i++;echo $index == 0 ? 'active' : '' ?><?php echo $i==$sizeList?' last':''?><?php echo $i==1?' first':''?>">
                <a href="#<?php echo $id . '-' . $tab['id'] ?>"
                   data-value="<?php echo $tab['value'] ?>"
                   data-type="<?php echo $tab['type'] ?>"
                   data-limit="<?php echo $this->getLimit() ?>"
                   data-column="<?php echo $this->getConfig('column') ?>"
                   data-row="<?php echo $this->getConfig('row') ?>"
                   data-cid="<?php echo $this->getData('category_ids') ?>"
                   data-template="<?php echo $template ?>"
                   data-carousel="<?php echo $this->getConfig('scroll') ?>">
                    <?php if($tab['label']=='bestsell'){
                        echo "top";
                    }else if($tab['label']=='discount'){
                        echo "sale";
                    }else{
                        echo $tab['label'];
                    }?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
    <div class="widget-tab-content tab-content">
        <?php foreach ($tabs as $index => $tab): ?>
        <div id="<?php echo $id . '-' . $tab['id'] ?>" class="tab-pane<?php echo $index == 0 ? ' active' : '' ?>">
            <?php if ($index > 0): ?>
        </div>
    <?php continue ?>
    <?php endif ?>
        <?php echo $this->renderCollection($tab['type'], $tab['value'], $template) ?>
    </div>
<?php endforeach ?>
</div>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mt/widget/frontend.js"></script>
<script type="text/javascript">
    new MT.Widget('<?php echo $id ?>', {
        animation: <?php echo $this->getConfig('animation') ?>,
        collectionUrl: '<?php echo $this->getUrl('mtwidget/collection/get') ?>',
        collectionCallback: function () {
        },
        spinnerClass: 'spinner',
        spinnerImg: '<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>',
        parallax: <?php echo $this->getConfig('parallax') ?>,
        carousel: <?php echo $this->getConfig('carousel') ?>,
        carouselConfig:  {itemsCustom: [
        [0,1],
        [320,1],
        [360,1],
        [480,2],
        [640,2],
        [768,2],
        [800,2],
        [980,2],
        [1024,3],
        [1280,3]
        ]
        },
        countdown: <?php echo $this->getConfig('countdown') ?>,
        countdownConfig: null,
        kenburns: <?php echo $this->getConfig('kenburns') ?>
    });
</script>
</div>
<?php //Mage::log(microtime() - $t) ?>
