<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Themes
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<?php
$enable = Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart');
?>
<?php $_cartQty = $this->getSummaryCount() ?>
<span class="mt-cart-loading">Loading...</span>
<div class="mt-cart">
	<div class="mt-icon-ajaxcart">
        <a class="mt-cart-label" href="<?php echo $this->getUrl('checkout/cart') ?>">
            <span class="heading-cart">
                    <span class="icon-cart">
                        <span class="icon-ecommerce icon-ecommerce-bag"></span>
                    </span>
                    <span class="mt-cart-title">My Bag</span>
                    <span class="print">
                         <span>Cart (<?php print (!empty($_cartQty)) ? $_cartQty : '0' ;?>)</span>
                    </span>
            </span>
        </a>
    </div>
	<div class="ajaxcart">
		<div class="search-form-border"></div>
        <?php
        $_items = $this->getRecentItems($_cartQty);
        if(count($_items)):
            ?>
		<div class="mt-ajax-container">
            <p><?php echo $this->__('Your cart')?></p>
            <ul class="clearfix">
                <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </ul>
		</div>
        <div class="mt-ajax-checkout">

            <?php if(Mage::getStoreConfig('opc/global/status')){?>
                <a class="checkout" href="<?php echo $this->getUrl('onepage') ?>"><span><?php echo $this->__('Checkout Now') ?></span></a>
            <?php }else{?>
                <a class="checkout" href="<?php echo $this->getCheckoutUrl() ?>"><span><?php echo $this->__('Checkout Now') ?></span></a>
            <?php }?>
            <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="view-cart">
                <span><?php echo $this->__('View cart') ?></span>
            </a>
        </div>
        <?php else: ?>
        <div class="mt-ajax-container">
            <p class="no-items-in-cart"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
        </div>
        <?php endif ?>
	</div>
</div>
<script type="text/javascript">
    var datatext = {};
    datatext.load = '<?php echo $this->__('processing');?>';
</script>