<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
$attributes = $this->getAttibuteOptions();
$id         = $this->getConfig('id');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
    <?php if ($title): ?>
        <h2><?php echo $title ?></h2>
    <?php endif ?>
    <ul class="<?php echo $scroll==1 ? 'owl-carousel ' : '' ?>">
        <?php foreach ($attributes as $attribute): ?>
            <li>
                <?php if (isset($attribute['link'])): ?>
                    <a href="<?php echo $attribute['link'] ?>" title="<?php echo $attribute['label'] ?>">
                <?php endif ?>
                <?php if ($attribute['image']): ?>
                    <?php if ($scroll == 1): ?>
                        <img class="lazyOwl" data-src="<?php echo $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" />
                    <?php else: ?>
                        <img src="<?php echo $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" />
                    <?php endif ?>
                <?php else: ?>
                    <span><?php echo $attribute['label'] ?></span>
                <?php endif ?>
                <?php if (isset($attribute['link'])): ?>
                    </a>
                <?php endif ?>
            </li>
        <?php endforeach ?>
    </ul>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mt/widget/frontend.js"></script>
    <script type="text/javascript">
        new MT.Widget('<?php echo $id ?>', {
            animation: <?php echo $this->getConfig('animation') ?>,
            parallax: <?php echo $this->getConfig('parallax') ?>,
            carousel: <?php echo $this->getConfig('carousel') ?>,
            carouselConfig: null,
            kenburns: <?php echo $this->getConfig('kenburns') ?>
        });
    </script>
</div>
