<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget_Collection */
$productCollection  = $this->getData('collection');
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $this->getData('carousel');
$row                = $this->getData('row');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper             = Mage::helper('catalog/image');
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i=0; foreach ($productCollection as $_product): ?>
        <?php /* @var $_product Mage_Catalog_Model_Product */ ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
        <?php endif ?>
        <?php $i++ ?>
        <li class="item">
            <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                <?php if ($carousel == 1): ?>
                    <img class="lazyOwl" data-src="<?php echo $helper->init($_product, 'small_image')->resize(135) ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                <?php else: ?>
                    <img src="<?php echo $helper->init($_product, 'small_image')->resize(135) ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                <?php endif ?>
            </a>
            <h3 class="product-name">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                    <?php echo $this->escapeHtml($_product->getName()) ?>
                </a>
            </h3>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <div class="product-date" data-date="<?php echo Mage::helper('mtwidget')->getDate($_product) ?>"></div>
        </li>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            </ul>
        <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
