<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Themes
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<div id="content" class="doc-content"><h2>Introduction</h2>
    <p><strong>Current Version</strong> 2.2.0 (Oct 09, 2013)</p>
    <blockquote>
        <p><strong><a href="http://www.magentothemes.net">MagentoThemes.Net</a></strong> always explores many <a href="http://www.magentothemes.net">magento themes</a> and gives you many surprise designs. And <strong><a href="http://www.magentothemes.net/hi-tech-responsive-magento-themes-mt-yoming.html">Hi-tech Magento Theme MT Yoming</a></strong> will be the best example. With unique design, impressive color and hamonious texture, <strong><a href="http://www.magentothemes.net/hi-tech-responsive-magento-themes-mt-yoming.html">MT Yoming</a></strong> is the perfect choice for any eCommerce website owners who always try to find out solutions that can boost up their sale and increase business growth.</p>
    </blockquote>
    <p>In this document, we will find step by step instructions for installing and using this template effectively. Thank you so much for paying much attention to this tutorial. We would like to help you if you have any question relating to this.</p>
    <h2>Help &amp; Support</h2>
    <hr>
    <h3> - References</h3>
    <hr>
    <p>You may find these sites useful while installing and configuring your Magento store:</p>
    <h4>   + Magento installation</h4>
    <hr>
    <ul>
        <li>Magento FAQ: <a href="http://www.magentocommerce.com/product/faq">http://www.magentocommerce.com/product/faq</a></li>
        <li>System Requirements: <a href="http://www.magentocommerce.com/system-requirements/">http://www.magentocommerce.com/system-requirements/</a></li>
        <li>Server Compatibility Check: <a href="http://www.magentocommerce.com/knowledge-base/entry/how-do-i-know-if-my-server-is-compatible-with-magento">http://www.magentocommerce.com/knowledge-base/entry/how-do-i-know-if-my-server-is-compatible-with-magento</a></li>
        <li>Installation Guide: <a href="http://www.magentocommerce.com/knowledge-base/entry/magento-installation-guide">http://www.magentocommerce.com/knowledge-base/entry/magento-installation-guide</a></li>
    </ul>
    <h4>   + Magento help</h4>
    <hr>
    <p><strong>Online Magento guide</strong></p>
    <ul>
        <li><p>Table of contents: <a href="http://www.magentocommerce.com/wiki/4_-_themes_and_template_customization/catalog/welcome_to_the_magento_user_s_guide">see the list of all topics</a></p>
        </li>
        <li><p>Selected topics: </p>
            <ol>
                <li><a href="http://www.magentocommerce.com/wiki/welcome_to_the_magento_user_s_guide/chapter_3">Categories, products and attributes</a> </li>
                <li><a href="http://www.magentocommerce.com/wiki/welcome_to_the_magento_user_s_guide/chapter_6">Customers</a> </li>
                <li><a href="http://www.magentocommerce.com/wiki/welcome_to_the_magento_user_s_guide/chapter_4">Payment, shipping and taxes</a> </li>
                <li><a href="http://www.magentocommerce.com/wiki/welcome_to_the_magento_user_s_guide/chapter_5">Promotions and marketing</a></li>
                <li><a href="http://go.magento.com/support/kb">Magento Go Knowledge Base</a></li>
            </ol>
        </li>
    </ul>
    <blockquote>
        <p>Magento Go differs from Magento Community Edition but most of the functionality is the same so this knowledge base might be very useful.</p>
    </blockquote>
    <ul>
        <li>Video Tutorials – Magento Go <a href="http://go.magento.com/video-tutorials">http://go.magento.com/video-tutorials</a></li>
        <li>Magento Wiki  <a href="http://www.magentocommerce.com/wiki/">http://www.magentocommerce.com/wiki/</a></li>
        <li>Magento Forum <a href="http://www.magentocommerce.com/boards/">http://www.magentocommerce.com/boards/</a></li>
        <li>stackoverflow.com <a href="http://stackoverflow.com/questions/tagged/magento">http://stackoverflow.com/questions/tagged/magento</a></li>
        <li>Magento Answers Stack Exchange <a href="http://magento.stackexchange.com/">http://magento.stackexchange.com/</a></li>
    </ul>
    <p>There are many tutorials, acticles and forums to help you learn how to use this Magento theme and its features.
        This section provides helpful links to instructions on commonly used this Magento template features, but you can learn even more by exploring these resources:</p>
    <ul>
        <li><p><strong>Demo MT Yoming</strong></p>
            <p>  <a href="http://themes.9magentothemes.com/mt_yoming/">http://themes.9magentothemes.com/mt_yoming/</a></p>
        </li>
        <li><p><strong>HelpDesk</strong></p>
            <p>  <a href="http://support.9magentothemes.com/open.php">http://support.9magentothemes.com/open.php</a></p>
        </li>
        <li><p><strong>Magento Fanpages</strong></p>
            <p>  <a href="http://www.facebook.com/magentothemes">http://www.facebook.com/magentothemes</a></p>
            <p>  <a href="https://twitter.com/9magentothemes">https://twitter.com/9magentothemes</a></p>
        </li>
    </ul>
    <p><strong>MT Yoming</strong> is not only a friendly interface, but also an impressive and beautyful design. So, It will surely meet the highest of your business objectives. With this user guide, we hope you will know how to install &amp; use this template daily to support your business activities effectively.</p>
    <p>If you are unable to find answers to your questions, please feel free to post them in <a href="http://support.9magentothemes.com/open.php">HelpDesk</a>, or contact to us. We’d be glad to help you. Once again thank you so much for using our company’s product.</p>
</div>